<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <EnablePackageValidation>true</EnablePackageValidation>
    <ImplicitUsings>disable</ImplicitUsings>
    <Title>Strong ID</Title>
    <Authors>Bradley Minogue</Authors>
    <Description>Wrapper classes for strong ID's</Description>
    <RepositoryUrl>https://github.com/minogb/StrongID</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>database; api; strong; type</PackageTags>
    <Version>1.0.3</Version>
    <PackageId>Minogb.Strong.ID</PackageId>
  </PropertyGroup>

</Project>
